### ISSUE TITLE
Use of forEach appears to break IE8

### ISSUE THREAD

**Issue by tomwasd** [iron-meteor/iron-controller#7]
I think its the use of forEach on line 43 of wait_list.js

Did a bit of digging and I don't believe IE8 supports forEach and so the routing all appears to fall over.

**Comment by lassombra** [comment]
I've separately discovered this same bug.  It is a major breaking bug breaking support on IE8.  PLEASE USE _.foreach

**Comment by chrisbutler** [comment]
fixed in https://github.com/iron-meteor/iron-controller/pull/9
